### ISSUE TITLE
nuevas festures

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#101]
Me gustaría abrir este issue para poder pensar en nuevas festures que se podrían añadir al backend

**Comment by Mrgaton** [comment]
Pensé en poder reprogramar el tiempo de expiración del documento después de qué alguien lo vea.

**Comment by inetol** [comment]
osea editar el tiempo de expiración?

**Comment by Mrgaton** [comment]
> osea editar el tiempo de expiración?

Tipo poder configurar otro tiempo de expiración aparte cuando alguien vea el documento por ejemplo poder configurar que el documento expire 30 segundos después de qué alguien lo lea

**Comment by Mrgaton** [comment]
Se podría hacer con otro número teniendo el tiempo y otro bool que indique si el documento fue leído y si no cuando llegue una request la bool de pondrá en true y el timespan será el tiempo actual más el que se pidió para eliminar el documento

**Comment by Mrgaton** [comment]
No se cómo veis la idea

**Comment by Mrgaton** [comment]
Como la función de burn after read de otro web pero más customizable

**Comment by Mrgaton** [comment]
Otra festure sería poder poner metadata como si fuera un .env un diccionario de string string, sería útil para poder configurar el sintax highlight que específico el usuario o para nuevas opciones que pueda guardar el frontend

**Comment by Mrgaton** [comment]
Y en la metadata el cliente podría especificar el title del documento o incluso una descripción de lo que hace más cualquier otra cosa
