### ISSUE TITLE
Funcionalidad con Elysia

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#107]
Quiero buscarle solución a la abstracción que hay montada encima de Elysia ya desde el commit #55 me he pasado por el forro de los huevos la mayoría de utilidades que proporciona el framework.

Si digo que es un problema es por como está construido ahora el backend basándose en varios issues antiguos, por ejemplo este no permite modificar la clase Elysia sin romper los types lo que restringe parte de los plugins, funciones como `.use()` y otros que modifiquen el typing dinámicamente en la clase. Aunque no ha supuesto ningún problema por ahora, ya es otra que se añade al carro de limitaciones y no sé si a este punto sería más sencillo usar Bun.serve() para construir una abstracción como hay en la librería y manejar todas las rutas de forma más nativa.

**Comment by tnfAngel** [comment]
> Quiero buscarle solución a la abstracción que hay montada encima de Elysia ya desde el commit #55 me he pasado por el forro de los huevos la mayoría de utilidades que proporciona el framework.
> 
> Si digo que es un problema es por como está construido ahora el backend basándose en varios issues antiguos, por ejemplo este no permite modificar la clase Elysia sin romper los types lo que restringe parte de los plugins, funciones como `.use()` y otros que modifiquen el typing dinámicamente en la clase. Aunque no ha supuesto ningún problema por ahora, ya es otra que se añade al carro de limitaciones y no sé si a este punto sería más sencillo usar Bun.serve() para construir una abstracción como hay en la librería y manejar todas las rutas de forma más nativa.

Eso supondría hacerlo prácticamente de 0, que opinas de Ntex?

**Comment by tnfAngel** [comment]
Si os parece bien cuando llegue a casa hago una pequeña versión para probar como iría

**Comment by inetol** [comment]
> Eso supondría hacerlo prácticamente de 0, que opinas de Ntex?

Ntex? Pero si es una framework para Rust

**Comment by inetol** [comment]
> Si os parece bien cuando llegue a casa hago una pequeña versión para probar como iría

OK, voy probando yo también como manejar las rutas

**Comment by tnfAngel** [comment]
> > Eso supondría hacerlo prácticamente de 0, que opinas de Ntex?
> 
> Ntex? Pero si es una framework para Rust

Por eso mismo, lo que propones supondría un rewrite bastante grande, vi Ntex y esta bastante bien, es muy simple y además es el mejor framework en tema de velocidad según  esto https://www.techempower.com/benchmarks/#section=data-r22&hw=ph&test=composite

**Comment by inetol** [comment]
Puede estar interesante, pero ten en cuenta que mi capacidad con Rust es limitado y no se si seria el lenguaje mas adecuado para el backend al ser de bajo nivel

**Comment by tnfAngel** [comment]
> Puede estar interesante, pero ten en cuenta que mi capacidad con Rust es limitado y no se si seria el lenguaje mas adecuado para el backend al ser de bajo nivel

Yo estoy aprendiendo, era por probar algo nuevo a ver que tal, y ya que jsp es relativamente "pequeño" pues encajaría un poco al no haber tanta complejidad, pero si no nada

**Comment by inetol** [comment]
He estado buscando otras alternativas, y la velocidad que pueda manejar el servidor web es una pajolera si luego esas requests tienen que estar a la espera de otras funciones como almacenar/leer del disco, esperar a requests externas o hacer consultas en la base de datos.

Más que buscar que servidor web la tiene más grande, prefiero buscar un lang que sea robusto y que permita tener un balance entre velocidad y practicabilidad, luego ya ver si podría ser buen candidato para el proyecto como de momento está siendo TS.

Por el momento voy haciendo esta prueba con Bun.serve(), ya si encuentro alguna mejor alternativa la propongo aquí

**Comment by tnfAngel** [comment]
> He estado buscando otras alternativas, y la velocidad que pueda manejar el servidor web es una pajolera si luego esas requests tienen que estar a la espera de otras funciones como almacenar/leer del disco, esperar a requests externas o hacer consultas en la base de datos.
> 
> Más que buscar que servidor web la tiene más grande, prefiero buscar un lang que sea robusto y que permita tener un balance entre velocidad y practicabilidad, luego ya ver si podría ser buen candidato para el proyecto como de momento está siendo TS.
> 
> Por el momento voy haciendo esta prueba con Bun.serve(), ya si encuentro alguna mejor alternativa la propongo aquí

tienes razón, me he flipado un poco con lo de Rust, ts va bastante bien y sobre todo con bun (era más un experimento que otra cosa lo del ntex)

**Comment by tnfAngel** [comment]
además aunque tengas capacidad de 10 millones de request por segundo mandando un hello world, al margen de factores internos como las consultas a la db o lecturas del disco, va a estar siempre capado por el reverse, el balancer y muchos otros factores fuera de nuestro control así que es un poco tontería

**Comment by Mrgaton** [comment]
Yo de rust se 0
