### ISSUE TITLE
Problema al subir documento

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#110]
Cuando intentas publicar un documento a  `api/v2/documents/` devuelve 404 osea si pones ese / al final no funciona no se si es un comportamiento deseado o que

**Comment by inetol** [comment]
No consigo replicar el error, prueba en ambas API para quitar la posibilidad de una configuración erronea:

* `https://jspaste.eu/api/v2/documents/`
* `https://paste.inetol.net/api/v2/documents/`

**Comment by Mrgaton** [comment]
No, es solo en la nueva pull request de trash everything (https://github.com/JSPaste/Backend/pull/108) perdon por no especificar

**Comment by inetol** [comment]
El estándar es tratar los backslashes al final del path de forma distinta (para poder diferenciar entre carpeta y fichero x ejemplo en un fileserver) y prefiero mantenerlo así.

https://hono.dev/api/hono#strict-mode
