### ISSUE TITLE
Serialización con JavaScriptCore

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#145]
Ya se llegó a mencionar esta implementación con anterioridad (https://github.com/JSPaste/Backend/issues/80#issuecomment-2050485943) como alternativa a Protobuf, pero a diferencia de CBOR no sé ¿~todavía si conforma alguna spec o la implementación es propia de WebKit~?[*](https://github.com/oven-sh/bun/blob/51257d56688cd44dba22aa384a80c76d59f5d33e/packages/bun-polyfills/src/modules/jsc.ts#L18) si hay librerías para serializar/deserializar este formato desde otros langs aparte de JavaScript.

El rendimiento de la implementación entre cbor-x y JSC es similar con la diferencia de que este último no bloquea el mismo event loop del runtime donde corre el resto del código, sino que funciona de *manera nativa* al estar implementado directamente en C++.

* https://github.com/oven-sh/bun/blob/51257d56688cd44dba22aa384a80c76d59f5d33e/packages/bun-polyfills/src/modules/jsc.ts#L11
* https://bun.sh/docs/api/utils#serialize-deserialize-in-bun-jsc
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
* https://html.spec.whatwg.org/multipage/structured-data.html

**Comment by tnfAngel** [comment]
es necesario el soporte con otros lenguajes? si es necesario y no hay soporte, siempre se puede escribir un serde

**Comment by Mrgaton** [comment]
que es un serde

**Comment by Mrgaton** [comment]
Si jsc es más rápido que cbor para mí es un sí roturno.

**Comment by inetol** [comment]
Decía lo del lang por la naturaleza de almacenar datos que sea posible leerlos desde otros sitios (future proof y eso), pero una vez se complete #83 ya *no será necesario serializar* cosa que no había pensado en su momento.
