### ISSUE TITLE
ErrorHandler not working?

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#151]
Probando con el codigo me di cuenta que cuando sucede un error no se evia ninguna informacion sobre el error.

![image](https://github.com/user-attachments/assets/7acd671a-0841-4a1b-af2a-7a15eac8e641)

**Comment by inetol** [comment]
Creo que no estás accediendo a la URL correcta de la API, sin más información como si la instancia es local o no, el codigo de error, y que pruebas se están realizando no puedo saber que significa.

**Comment by Mrgaton** [comment]
Es local si y sucede cuando subo un documento mayor que el doc max size directamente no me dice nada y sale eso alomejor es un error de thunder client pero no creo.

**Comment by inetol** [comment]
No debería de ocurrir esto, ahora lo pruebo

**Comment by inetol** [comment]
No consigo replicar el error:

![Screenshot](https://github.com/user-attachments/assets/fa7b7b6b-27b7-43c8-bdb8-17229efc3170)

Especifica toda la configuración que estés utilizando para ejecutar las pruebas...

**Comment by inetol** [comment]
Cierro este issue porque no he conseguido replicar el problema
