### ISSUE TITLE
Replace brotli with zstd

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#162]
Reviviendo la discusión cuando se quería sustituir DEFLATE por brotli, se mencionó sustituirlo directamente por zstd, pero no sabía como manejar la implementación correctamente.

Se puede utilizar primero los binarios nativos del sistema, en caso de que no estén presentes usar un módulo WASM o un binario compatible como [`@mongodb-js/zstd`](https://www.npmjs.com/package/@mongodb-js/zstd)

**Comment by Mrgaton** [comment]
brotli y zstd son muy parecidos creo que zstd le gana por poco a brotli en su maximo nivel pero no se si eso mereze la pena

**Comment by Mrgaton** [comment]
crea unos benchmarks y si es mas rápido y comprime mejor lo integramos para la v3

**Comment by inetol** [comment]
El problema no es tanto cuanto puede comprimir, sino la eficiencia de este porque con brotli hay problemas en la latencia y el uso de la CPU. Hay un issue en https://github.com/oven-sh/bun/issues/7418 para exponer la librería de zstd

**Comment by Mrgaton** [comment]
Si usamos zstd a su maximo nivel me parece bien. Aparte que una librería en nativo siempre es mejor, ponlo como objetivo para la v3

**Comment by Mrgaton** [comment]
@inetol podrias hacer un codigo para testear ambos la velocidad y el ratio de compression en distintos niveles?

**Comment by inetol** [comment]
Con que pruebo zstd? Los módulos WASM siempre serán más lentos, por lo que no me parece una comparación justa (y los de `@mongodb-js/zstd` tampoco me convencen demasiado). Puedo hacerlo con los binarios de brotli y zstd, pero de eso hay benchmarks por un tubo

**Comment by Mrgaton** [comment]
De parte de brotli prueba la implementación actúal del servidor y de parte de zstd la más rápida que exista en la librería.

**Comment by inetol** [comment]
De momento hasta que no se exponga la utilidad no voy a mirármelo mucho esto

**Comment by inetol** [comment]
Este issue ya no es relevante https://github.com/JSPaste/Backend/pull/189/commits/34c5056f898f351921eaa6c963162c83c5c6411e
