### ISSUE TITLE
Backend broken

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#169]

**Comment by inetol** [comment]
Se me rompió la bola de cristal por lo que no puedo saber qué se ha roto en el Backend

**Comment by Mrgaton** [comment]
La api ya no la lleva angel?

**Comment by tnfAngel** [comment]
Si te refieres a jspaste.eu, de momento hace redirect a https://paste.inetol.net/ porque dio problemas en el podman y no he tenido tiempo de revisarlo

**Comment by Mrgaton** [comment]
Por fin ángel arreglo podman ?

**Comment by inetol** [comment]
![screenshot](https://github.com/user-attachments/assets/eab4d1b5-c3cc-4acd-b330-092fb32d1f45)

**Comment by tnfAngel** [comment]
fixed
