### ISSUE TITLE
Especificación OpenAPI incompleta

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#19]
El fichero que devuelve https://jspaste.eu/docs/json no tiene un formato correcto o está incompleto, ahora mismo estoy corrigiendo ni que sea introduciendo campos vacíos para poder continuar con la transición de la librería.

**Comment by tnfAngel** [comment]
que es lo que falla exactamente?

**Comment by inetol** [comment]
El IDE me marcaba el fichero como si la especificación fuera inválida, ahora volviendo a abrir el fichero solo que faltan varios campos como descripciones o referencias, quizás por los "objetos" que hay en las rutas en vez del estandar ":cosa" se haya pensado que era otra cosa.

*Si parece que hay parámetros inválidos dentro de la especificación, aunque no son graves*

**Comment by inetol** [comment]
Ya debería estar solucionado desde hace unos commits
