### ISSUE TITLE
Cifrar documentos protegidos por contraseña con la propia contraseña

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/Backend#21]
Esto eliminaría la necesidad de guardar las contraseñas en texto plano dentro del documento, haría mas seguros los documentos que tienen contraseña y se necesitaría una flag de hasPassword en vez de lo que hay ahora

**Comment by Mrgaton** [comment]
es inutil en mi opinion

**Comment by Mrgaton** [comment]
y solo haria todo mas lento

**Comment by Mrgaton** [comment]
Pero bueno, si se supone que es open source, y que esta echo para que la gente haga sus servidores pues bueno, añadiria una capa más de seguridad.

**Comment by Mrgaton** [comment]
Yo no lo haría, pero si al final se hace usaría un algoritmo rápido, no hace falta mucha seguridad aquí, ya que nadie subiría algo realmente sensible aquí

**Comment by inetol** [comment]
Yo sugiero que se use la contraseña para encriptar el Buffer y el secret y guardar el hash de la misma en el documento para validarlo sin tener que desencriptar todo el bloque. Habrá mejores formas en client side con alguna llave maestra para encriptar todo lo que vaya hacia el servidor, algo parecido a lo que hace Cryptomator sin que el backend haga nada

**Comment by Mrgaton** [comment]
de echo se puede encriptar el contenido perfectamente desde el cliente y no hacer absoultamente nada en el backend seria una buena idea si

**Comment by tnfAngel** [comment]
> es inutil en mi opinion

no del todo, imagínate que por algún casual se filtran los documentos, por alguna vulnerabilidad o algo, estos incluyen las contraseñas, no están asociadas a ningún usuario, vale, pero siguen siendo contraseñas, y están en texto plano, igual que el contenido, eso es un riesgo de seguridad. Btw lo del client-side me parece bien, así también la comunicación con el servidor va más encriptada (aunque ya se use TLS etc)

**Comment by Mrgaton** [comment]
entonces guarda las contraseñas como hash eso si no estaria mal

**Comment by tnfAngel** [comment]
> entonces guarda las contraseñas como hash eso si no estaría mal

pero también aprovechar y cifrar lo demás

**Comment by Mrgaton** [comment]
sigo teniendo mis dudas sobre lo otro

**Comment by inetol** [comment]
Hace unos días estaba probando en otra rama mejores formas de estructurar los documentos. Me quede con la duda de si *realmente* es necesario protobuf para *solo* estructurar los documentos, ya que para lo que se usa se podría simplificar todo a una sola interface
