### ISSUE TITLE
No se devuelve un errorCode cuando accedo a un documento que no existe

### ISSUE THREAD

**Issue by nulkode** [JSPaste/Backend#26]
Cuando intento acceder a un documento que no existe, como [este](https://jspaste.eu/api/v2/documents/non-existentid), en vez de devolver un body con el tipo de respuesta, un código de error y un mensaje, me devuelve `{"type":"headers"}`. Creo que esto no debería estar ocurriendo.

**Comment by tnfAngel** [comment]
fixed in c68545b1ffefe8963537de03edc7df46c912b3c4
