### ISSUE TITLE
env -madness

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#40]
Llevo toda la tarde pensando una forma de manejar y sanitizar los env. Cuando ayer encontré [esto](https://bun.sh/docs/runtime/env#typescript) pensaba que Bun se encargaría de todo y tendría la vida hecha (no leí lo de "treat a variable as a non-optional string" y ahora XOXO). Intentar hacer apaños con los comparadores como que no y se estaría volviendo a la raíz de por qué hice el rework de los env.

Tengo ahora mismo dos soluciones a esto y ambas no me gustan demasiado...

### Validar env:
* Que *ese* método mágico transforme a los types que tocan basado en su primitivo definido en la interficie Env (y en caso de no serlo manejarlo con un Throw o sustituyendo por el valor predeterminado de ese env). No sería demasiado difícil implementar esto ??, pero hay que probarlo y validar más de lo que me gustaría para una cosa tan simple como unas variables de entorno. De aquí viene la otra idea...

### Fichero de configuración:
* De esto ya lo probé antes del rework y me parecía muchísima mejor idea hasta que me di cuenta de que se tendría que matar el soporte de los env, cosa que aparte de joder cierta configuración, dejaría el contenedor con la configuración predeterminada sin posibilidad de cambiarse (se podría exponer el fichero de configuración).

Me urge arreglar esto porque sigue algún env funcionando incorrectamente y no voy a añadir más chapuzas, si hay alguna idea de como solucionar esto dejadlo aquí.

**Comment by tnfAngel** [comment]
es realmente necesario validar y sanitizar los env? creo que bastaría con debuggear que variable no funciona, no? al final configurar las variables correctamente es responsabilidad del desarrollador, si es realmente necesario, quizás usar env validado y el archivo de configuración como fallback (en caso de undefined o tipo incorrecto), dicho esto, sería sencillo validarlo (de hecho, creo que ni siquiera se necesita programar nada, se puede usar algo como [typia](https://typia.io/docs/validators/assert/))

**Comment by inetol** [comment]
> es realmente necesario validar y sanitizar los env? creo que bastaría con debuggear que variable no funciona, no? al final configurar las variables correctamente es responsabilidad del desarrollador, si es realmente necesario, quizás usar env validado y el archivo de configuración como fallback (en caso de undefined o tipo incorrecto), dicho esto, sería sencillo validarlo (de hecho, creo que ni siquiera se necesita programar nada, se puede usar algo como [typia](https://typia.io/docs/validators/assert/))

El fallback del fichero de config tampoco se podría hacer, esos env son puro string o undefined aunque les cambies el type internamente seguirán siendo string o undefined.

Imaginemos que los env deben tener el mayor peso para sobreescribir la config que haya por debajo, luego tendríamos el fichero de configuración y finalmente el "por defecto" interno, estamos en las mismas teniendo que transformar ese env para que sea comparable con lo que haya en el fichero de config, lo mismo para los "por defecto", solo se añadiría un paso intermedio. Intentar usar booleanos en los env es de risa si no creas un método dedicado para devolver el primitivo verdadero (o manejar la respuesta si no es un booleano ZZZ) y así poder decidir si usar o no la configuración por defecto.

**Comment by tnfAngel** [comment]
> > es realmente necesario validar y sanitizar los env? creo que bastaría con debuggear que variable no funciona, no? al final configurar las variables correctamente es responsabilidad del desarrollador, si es realmente necesario, quizás usar env validado y el archivo de configuración como fallback (en caso de undefined o tipo incorrecto), dicho esto, sería sencillo validarlo (de hecho, creo que ni siquiera se necesita programar nada, se puede usar algo como [typia](https://typia.io/docs/validators/assert/))
> 
> El fallback del fichero de config tampoco se podría hacer, esos env son puro string o undefined aunque les cambies el type internamente seguirán siendo string o undefined.
> 
> Imaginemos que los env deben tener el mayor peso para sobreescribir la config que haya por debajo, luego tendríamos el fichero de configuración y finalmente el "por defecto" interno, estamos en las mismas teniendo que transformar ese env para que sea comparable con lo que haya en el fichero de config, lo mismo para los "por defecto", solo se añadiría un paso intermedio. Intentar usar booleanos en los env es de risa si no creas un método dedicado para devolver el primitivo verdadero (o manejar la respuesta si no es un booleano ZZZ) y así poder decidir si usar o no la configuración por defecto.

cierto, no había caído en eso

**Comment by tnfAngel** [comment]
> > es realmente necesario validar y sanitizar los env? creo que bastaría con debuggear que variable no funciona, no? al final configurar las variables correctamente es responsabilidad del desarrollador, si es realmente necesario, quizás usar env validado y el archivo de configuración como fallback (en caso de undefined o tipo incorrecto), dicho esto, sería sencillo validarlo (de hecho, creo que ni siquiera se necesita programar nada, se puede usar algo como [typia](https://typia.io/docs/validators/assert/))
> 
> El fallback del fichero de config tampoco se podría hacer, esos env son puro string o undefined aunque les cambies el type internamente seguirán siendo string o undefined.
> 
> Imaginemos que los env deben tener el mayor peso para sobreescribir la config que haya por debajo, luego tendríamos el fichero de configuración y finalmente el "por defecto" interno, estamos en las mismas teniendo que transformar ese env para que sea comparable con lo que haya en el fichero de config, lo mismo para los "por defecto", solo se añadiría un paso intermedio. Intentar usar booleanos en los env es de risa si no creas un método dedicado para devolver el primitivo verdadero (o manejar la respuesta si no es un booleano ZZZ) y así poder decidir si usar o no la configuración por defecto.

esto está interesante: https://github.com/Svehla/typed-env-parser

**Comment by inetol** [comment]
hmm aparentemente soluciona todos los problemas que presenta el uso de env. Voy a probar con eso a ver si ya consigo limpiar este issue
