### ISSUE TITLE
Rework routes

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#52]
En vez de inicializar Elysia en cada ruta, porque no convertir esas funciones en clases y que sean inicializadas desde Server usando ya su propio "Elysia" para centralizarlo un poco? Si hay algún motivo para no hacerlo por tema de child processes o rendimiento no sé completamente como se organiza Elysia por dentro.

*¿Podría estar relacionado con #51 al inicializar varios servidores de Elysia en las rutas y cargarlos dinámicamente?*

**Comment by tnfAngel** [comment]
Elysia esta diseñado para inicializarse en cada ruta
![imagen](https://github.com/JSPaste/Backend/assets/57068341/5b96e3f7-743d-48bb-82d4-4b907e2b08db)
Pero quizas se pueda hacer de otra forma

**Comment by inetol** [comment]
Hice lo de las clases y *aparentemente* funcionaba correctamente (desconozco lo del issue 51), si eso hago un PR de prueba todo lleno de clases y se compara

**Comment by tnfAngel** [comment]
Por cierto, elysia actualmente tiene un límite de ~40 rutas por instancia (se que no se va a superar btw)
![imagen](https://github.com/JSPaste/Backend/assets/57068341/9e373428-505c-4282-95c3-69483c5bcc63)

**Comment by inetol** [comment]
Se podría hacer una instancia por versión de la API a las malas (o una instancia por ruta y ya como ahora), lo que sí parece es que tener dos instancias es más lento(?) al menos al inicio

**Comment by inetol** [comment]
Hay varios plugins para manejar rutas *([elysia-group-router](https://github.com/itsyoboieltr/elysia-group-router) [elysia-autoroutes](https://github.com/wobsoriano/elysia-autoroutes) [elysia-autoload](https://github.com/kravetsone/elysia-autoload))*, pero es lo mismo que se está haciendo ahora importando todo lo que haya en una carpeta añadiendo un toque a NextJS y algo más de simplificación.

Lo único que me llama la atención es que todos estos plugins prefieren que uses la misma instancia de Elysia en las rutas.

**Comment by tnfAngel** [comment]
Esos plugins pueden estar interesantes, voy a ver qué tal

**Comment by inetol** [comment]
El único que podría ser interesante es el autoload para el Eden y no tener tanto lío en las rutas, pero ese plugin tiene algún que otro problema de estabilidad que cada dos por tres se rompe y deja de funcionar.

**Comment by tnfAngel** [comment]
btw como se haría el /documents normal, que tiene la última versión de la Api?

**Comment by inetol** [comment]
Magia, supongo que tendrá algún alias. De momento iré cambiando las rutas actuales para que no vaya inicializando nuevos Elysia ~~y ya se verá si sale a cuenta hacer lo de las clases.~~
