### ISSUE TITLE
Favicon no visible en las docs

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/Backend#77]
Quizás es un poco irrelevante, pero algunos navegadores usan como fallback "/favicon.ico" para cargar el favicon, y dado que las docs o la api no tienen link rel='icon', no van a tener favicon, lo mismo pasa con el archivo /robots.txt (de momento no presente)

entiendo que la carpeta images sea para organizar y evitar un poco colisionar con el espacio de claves, pero estaría bien tener también el favicon.ico de fallback en la carpeta public (quizas con un enlace simbólico a /images/favicon.ico?)

**Comment by inetol** [comment]
*Se puede* de forma cutre con un enlace simbólico a "/image/favicon.svg" y el navegador se la suda la extensión que tenga que lo va a mostrar igual, pero creo que deja especificar directamente en el swagger la ubicación del favicon.

**Comment by tnfAngel** [comment]
> _Se puede_ de forma cutre con un enlace simbólico a "/image/favicon.svg" y el navegador se la suda la extensión que tenga que lo va a mostrar igual, pero creo que deja especificar directamente en el swagger la ubicación del favicon.

Lo decía no solo por swagger, pero también por los endpoints de la api y, sobre todo, el raw, pero bueno tampoco es muy importante (con que se pueda hacer de forma nativa en swagger ya es suficiente y lo demas tampoco tiene tanta importancia ig)

**Comment by inetol** [comment]
Si es muy necesario también se puede hacer un 301 del servidor web de /favicon.ico hacia /image/favicon.svg, ahora me miro que hago con lo del favicon

**Comment by tnfAngel** [comment]
estuve mirando en la config de scalar https://github.com/scalar/scalar/blob/main/packages/api-reference/README.md/#metadata-object

sin embargo no encuentro lo relacionado con el favicon

por cierto si se va a hacer un redirect, con next.js se puede hacer facilmente en la config (aunque este no use 301 especificamente, devolveria 308, pero seguro funciona)

**Comment by inetol** [comment]
Recuerdo que las docs se encuentran en el backend por lo que Nexjs nl tendria nada que ver, lo mas limpio que se me ocurre es hacer un redirect con Elysia

**Comment by tnfAngel** [comment]
> Recuerdo que las docs se encuentran en el backend por lo que Nexjs nl tendria nada que ver, lo mas limpio que se me ocurre es hacer un redirect con Elysia

pero next.js controla el / y por lo tanto /favicon.ico, elysia el /docs y /api (antes era docs.jspaste.eu pero ya no) (hablando del sitio principal, eso ya depende de como se monte)

**Comment by inetol** [comment]
> pero next.js controla el / y por lo tanto /favicon.ico, elysia el /docs y /api (antes era docs.jspaste.eu pero ya no) (hablando del sitio principal, eso ya depende de como se monte)

Claro es verdad

**Comment by inetol** [comment]
> estuve mirando en la config de scalar https://github.com/scalar/scalar/blob/main/packages/api-reference/README.md/#metadata-object
> 
> sin embargo no encuentro lo relacionado con el favicon
> 
> por cierto si se va a hacer un redirect, con next.js se puede hacer facilmente en la config (aunque este no use 301 especificamente, devolveria 308, pero seguro funciona)

Si, con eso no hay problema

**Comment by tnfAngel** [comment]
entonces yo lo que decia era hacer un symlink en la carpeta public de ./favicon.ico a -> ./images/favicon.svg, que seria mejor, el redirect o el symlink?

**Comment by inetol** [comment]
El redirect

**Comment by tnfAngel** [comment]
👍 [49a3e65](https://github.com/JSPaste/Frontend/commit/49a3e65c35e70ac997e907f5fc928b31c3724512)
