### ISSUE TITLE
Lifetime no se guarda correctamente?

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#80]
Creo que el lifetime no funciona correctamente, ya que subo un documento y cuando acedo a él siempre me pone el lifetime a 0, y cuando intento usarlo en local siempre me autoelimina el documento si especifico algún lifetime que no sea el default.

**Comment by inetol** [comment]
No solo puedo confirmar esto sino que parece que la documentación del swagger se ha jodido al menos para el endpoint de Publish

**Comment by tnfAngel** [comment]
Cuando regrese a casa miro

**Comment by tnfAngel** [comment]
el error se debe a que document.expirationTimestamp es la clase Long, y en  https://github.com/JSPaste/Backend/blob/dev/src/classes/DocumentHandler.ts#L211 se está comparando la clase con un primitivo (y ts no dice nada porque  DocumentDataStruct.expirationTimestamp es de tipo any)

**Comment by tnfAngel** [comment]
~voy a arreglarlo provisionalmente usando Long.toInt() - lo ideal sería arreglar los tipos de IDocumentDataStruct.expirationTimestamp~ arreglado

**Comment by tnfAngel** [comment]
lo que no entiendo es por que se usa long en vez de bigint - esto causa una discrepancia en los tipos

**Comment by inetol** [comment]
Long aparte de ser el estándar menos para ToyScript, es también el tipo "Long" para protobuf. bigint es el apaño de Typescript y creo que no es intercambiable con la implementación de Long de protobuf (ya que está pensado para usarse con JS etc), y si lo es no me sale registrado.

**Comment by tnfAngel** [comment]
Bigint no es de JS? igualmente yo creo que tampoco hace falta usar bigint - nunca habrán timestamps tan grandes, aunque claro si hay que acomodarse al estándar de protobuf en JS...

**Comment by inetol** [comment]
Hasta 2100 y algo, pero es costumbre usar los long además que si lo fuerza el estándar ya te tiras de cabeza a usarlos

**Comment by tnfAngel** [comment]
Ya, no se que tan necesario sea protobuf en este proyecto escrito en TS, pero bueno, de momento iremos tirando con esto supongo

**Comment by inetol** [comment]
A ver, acabo de revisar la spec de Protobuf y no está oficialmente soportado JS/TS. El port de protobufjs no estaba hecho por Google oficialmente aunque lo hubiese dicho en algún momento. Aunque para protobuf ya tengo un sustituto mucho más rápido y simple.

Ah, y la implementación que usa protobuf es esta usando un polyfill chusta: https://www.npmjs.com/package/long

**Comment by Mrgaton** [comment]
Que alternativas tenéis a protobufers

Yo lo escoji por qué es una forma rápida y simple de serializar una estructura de datos a binario.

**Comment by inetol** [comment]
En Bun "nativo" de JavaScriptCore tiene unas funciones para serializar que no están mal, pero haciendo benchmarks y probando diferentes implementaciones con diferentes estándares encontré la mejor alternativa que además ya lleva tiempo definido en un RFC, mirad esto https://github.com/kriszyp/cbor-x

**Comment by Mrgaton** [comment]
Y eso es más rápido y ocupada menos espacio que protobufers?

**Comment by inetol** [comment]
TestStruct.proto:
```proto
syntax = "proto3";

option optimize_for = SPEED;

message TestStruct {
  string data = 1;
  string anotherData = 2;
}
```

Benchmark (sin datos):
```ts
import { decode, encode } from 'cbor-x';
import { bench, group, run } from 'mitata';
import { TestStruct } from './structures/Structures';

const document = {
	data: '...',
	anotherData: '...'
};

const protobufDocument: Uint8Array = TestStruct.encode(document).finish();
const cborDocument: Buffer = encode(document);

group('Serialization encoding', () => {
	bench('Protobufjs', () => TestStruct.encode(document).finish());
	bench('CBOR-X', () => encode(document));
});

group('Serialization decoding', () => {
	bench('Protobufjs', () => TestStruct.decode(protobufDocument));
	bench('CBOR-X', () => decode(cborDocument));
});

await run();

console.info('\nProtobufjs byte length:', protobufDocument.byteLength);
console.info('CBOR-X byte length:', cborDocument.byteLength);
```

![Screenshot](https://github.com/JSPaste/Backend/assets/34861290/b75e20fd-3b9b-4f77-ab64-4f5623905b1e)

El tamaño ocupan similar al menos usando strings, pero el resto puedes ver el margen de mejora y si no te lo crees aquí dejo el [benchmark.js.zip](https://github.com/JSPaste/Backend/files/14957758/benchmark.js.zip) (ejecutar solo con Bun)

**Comment by Mrgaton** [comment]
Bueno no esta mal

y vaya codigo el de benchmark.js

**Comment by Mrgaton** [comment]
Aunque yo creo que deveriamos probarlos con buffers tambien ya que es lo que se va a guardar en realidad en los documentos

**Comment by Mrgaton** [comment]
vale hize pruebas y es perfecto

**Comment by Mrgaton** [comment]
Yo ya cerraría este issue
