### ISSUE TITLE
Validation failed, please check our documentation

### ISSUE THREAD

**Issue by Mrgaton** [JSPaste/Backend#82]
Al parecer el problema del long ahora tambien sucede en la api de acess v2 ya que devuelve un long cuando espera un numero
![image](https://github.com/JSPaste/Backend/assets/68958481/9e9d83a6-44be-45aa-87af-6468f778d7df)

Por lo que veo expirationTimestamp es null

**Comment by tnfAngel** [comment]
el problema del timestamp no era en publish, era en access que al comprobarlo lo borraba automáticamente

**Comment by Mrgaton** [comment]
me refiero que ahora cuando acedes al documento sale este error

```
{"type":"internal","code":1002,"message":"Validation failed, please check our documentation"}
```

ya que espera un numero en expiration timespan

		expirationTimestamp: t.Optional(
								t.Numeric({
									description:
										'UNIX timestamp with the expiration date in milliseconds. Undefined if the document is permanent.',
									examples: [60, 0]
								})
							)


pero document.timespan es null

**Comment by Mrgaton** [comment]
con la nueva pull request que hize esto deveria estar solucionado
