### ISSUE TITLE
Binarios

### ISSUE THREAD

**Issue by inetol** [JSPaste/Backend#96]
Ahora que ya está disponible [esta](https://bun.sh/docs/bundler/executables#cross-compile-to-other-platforms) funcionalidad sería interesante, aparte de lanzar versiones estables de los contenedores también lanzar binarios pre compilados.

Por el momento sería pre compilar a estas arquitecturas:
* bun-darwin-arm64
* bun-linux-arm64
* bun-linux-x64
* bun-windows-x64

**Comment by Mrgaton** [comment]
Esto se puede hacer automáticamente con git actions?

**Comment by inetol** [comment]
Sí, igual que construye los contenedores, pues construir binarios y lanzar releases automáticamente

**Comment by Mrgaton** [comment]
Estaría bien que lo haga en cada comit en stable no se cómo lo veis
